# Generated by Django 3.1 on 2021-02-14 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastMeteodata',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время')),
                ('place', models.BigIntegerField(verbose_name='Код места')),
                ('placeName', models.CharField(max_length=80, verbose_name='Место')),
                ('temperature', models.FloatField(verbose_name='Температура воздуха')),
                ('wind_way', models.BigIntegerField(verbose_name='Направление ветра')),
                ('wind_speed', models.FloatField(verbose_name='Скорость ветра')),
                ('air_pressure', models.FloatField(verbose_name='Атмосферное давление')),
                ('water_pressure', models.FloatField(verbose_name='Давление моря')),
                ('weather', models.TextField(verbose_name='Погодное явление')),
            ],
            options={
                'verbose_name': 'Спрогнозированные метеоданные',
                'verbose_name_plural': 'Спрогнозированные метеоданные',
            },
        ),
        migrations.CreateModel(
            name='Meteodata',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время')),
                ('place', models.BigIntegerField(verbose_name='Код места')),
                ('placeName', models.CharField(max_length=80, verbose_name='Место')),
                ('temperature', models.FloatField(verbose_name='Температура воздуха')),
                ('wind_way', models.BigIntegerField(verbose_name='Направление ветра')),
                ('wind_speed', models.FloatField(verbose_name='Скорость ветра')),
                ('air_pressure', models.FloatField(verbose_name='Атмосферное давление')),
                ('water_pressure', models.FloatField(verbose_name='Давление моря')),
                ('weather', models.TextField(verbose_name='Погодное явление')),
            ],
            options={
                'verbose_name': 'Метеоданные',
                'verbose_name_plural': 'Метеоданные',
            },
        ),
        migrations.CreateModel(
            name='MeteodataAnomalies',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('meteodata_id', models.BigIntegerField(verbose_name='Код записи')),
                ('fieldname', models.TextField(verbose_name='Название поля')),
                ('value', models.TextField(verbose_name='Значение')),
                ('anomaly', models.TextField(verbose_name='Аномалия')),
            ],
            options={
                'verbose_name': 'Аномалии',
                'verbose_name_plural': 'Аномалии',
            },
        ),
    ]
