# Generated by Django 3.2.7 on 2022-11-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteodata', '0002_alter_neuralnet_file_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeteodataAnomalies',
        ),
        migrations.AddField(
            model_name='forecastmeteodata',
            name='place_name',
            field=models.CharField(default='-', max_length=80, verbose_name='Place_name'),
            preserve_default=False,
        ),
    ]
