# Generated by Django 3.2.7 on 2022-12-01 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meteodata', '0003_auto_20221123_1936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='test_date',
            new_name='datetime',
        ),
    ]
