# Generated by Django 3.1 on 2021-03-22 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteodata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClearForecastMeteodata',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время')),
                ('place', models.BigIntegerField(verbose_name='Код места')),
                ('placeName', models.CharField(max_length=80, verbose_name='Место')),
                ('temperature', models.FloatField(verbose_name='Температура воздуха')),
                ('wind_way', models.BigIntegerField(verbose_name='Направление ветра')),
                ('wind_speed', models.FloatField(verbose_name='Скорость ветра')),
                ('air_pressure', models.FloatField(verbose_name='Атмосферное давление')),
                ('water_pressure', models.FloatField(verbose_name='Давление моря')),
                ('weather', models.TextField(verbose_name='Погодное явление')),
            ],
            options={
                'verbose_name': 'Чистые спрогнозированные метеоданные',
                'verbose_name_plural': 'Чистые спрогнозированные метеоданные',
            },
        ),
        migrations.CreateModel(
            name='ClearMeteodata',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время')),
                ('place', models.BigIntegerField(verbose_name='Код места')),
                ('placeName', models.CharField(max_length=80, verbose_name='Место')),
                ('temperature', models.FloatField(verbose_name='Температура воздуха')),
                ('wind_way', models.BigIntegerField(verbose_name='Направление ветра')),
                ('wind_speed', models.FloatField(verbose_name='Скорость ветра')),
                ('air_pressure', models.FloatField(verbose_name='Атмосферное давление')),
                ('water_pressure', models.FloatField(verbose_name='Давление моря')),
                ('weather', models.TextField(verbose_name='Погодное явление')),
            ],
            options={
                'verbose_name': 'Чистые метеоданные',
                'verbose_name_plural': 'Чистые метеоданные',
            },
        ),
    ]
